/*
 * Click nbfts://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica0108;

/**
 *
 * @author Dell
 */
public class Calculadora extends javax.swing.JFrame {

    String operadores[] = {"/", "+", "-", "*", "%"};
    double num = 0;
    double num2 = 0;
    String NumText = "";

    double resultado;
    String operacionActual = "";
    boolean introduciendoNumero = false;
    boolean operacionFinalizada = false;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        lblPantalla.setText(NumText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiarMemoria = new javax.swing.JButton();
        btnPorciento = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnCambioSigno = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        numPantalla = new javax.swing.JTextField();
        lblPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Maho Edition");

        btnLimpiarMemoria.setBackground(new java.awt.Color(51, 51, 51));
        btnLimpiarMemoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLimpiarMemoria.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarMemoria.setText("CE");

        btnPorciento.setBackground(new java.awt.Color(51, 51, 51));
        btnPorciento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPorciento.setForeground(new java.awt.Color(255, 255, 255));
        btnPorciento.setText("%");
        btnPorciento.setMaximumSize(new java.awt.Dimension(49, 25));
        btnPorciento.setMinimumSize(new java.awt.Dimension(49, 25));
        btnPorciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcientoActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(51, 51, 51));
        btnBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("<--");
        btnBorrar.setMaximumSize(new java.awt.Dimension(49, 25));
        btnBorrar.setMinimumSize(new java.awt.Dimension(49, 25));

        btnDivision.setBackground(new java.awt.Color(51, 51, 51));
        btnDivision.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("/");
        btnDivision.setMaximumSize(new java.awt.Dimension(49, 25));
        btnDivision.setMinimumSize(new java.awt.Dimension(49, 25));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnMultiplicacion.setBackground(new java.awt.Color(51, 51, 51));
        btnMultiplicacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiplicacion.setText("X");
        btnMultiplicacion.setMaximumSize(new java.awt.Dimension(49, 25));
        btnMultiplicacion.setMinimumSize(new java.awt.Dimension(49, 25));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnOcho.setBackground(new java.awt.Color(102, 102, 102));
        btnOcho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOcho.setForeground(new java.awt.Color(51, 51, 51));
        btnOcho.setText("8");
        btnOcho.setMaximumSize(new java.awt.Dimension(49, 25));
        btnOcho.setMinimumSize(new java.awt.Dimension(49, 25));
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnSiete.setBackground(new java.awt.Color(102, 102, 102));
        btnSiete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSiete.setForeground(new java.awt.Color(51, 51, 51));
        btnSiete.setText("7");
        btnSiete.setMaximumSize(new java.awt.Dimension(49, 25));
        btnSiete.setMinimumSize(new java.awt.Dimension(49, 25));
        btnSiete.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnResta.setBackground(new java.awt.Color(51, 51, 51));
        btnResta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 255, 255));
        btnResta.setText("-");
        btnResta.setMaximumSize(new java.awt.Dimension(49, 25));
        btnResta.setMinimumSize(new java.awt.Dimension(49, 25));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnSeis.setBackground(new java.awt.Color(102, 102, 102));
        btnSeis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(51, 51, 51));
        btnSeis.setText("6");
        btnSeis.setMaximumSize(new java.awt.Dimension(49, 25));
        btnSeis.setMinimumSize(new java.awt.Dimension(49, 25));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(102, 102, 102));
        btnCinco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(51, 51, 51));
        btnCinco.setText("5");
        btnCinco.setMaximumSize(new java.awt.Dimension(49, 25));
        btnCinco.setMinimumSize(new java.awt.Dimension(49, 25));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnCuatro.setBackground(new java.awt.Color(102, 102, 102));
        btnCuatro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCuatro.setForeground(new java.awt.Color(51, 51, 51));
        btnCuatro.setText("4");
        btnCuatro.setMaximumSize(new java.awt.Dimension(49, 25));
        btnCuatro.setMinimumSize(new java.awt.Dimension(49, 25));
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnSuma.setBackground(new java.awt.Color(51, 51, 51));
        btnSuma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("+");
        btnSuma.setMaximumSize(new java.awt.Dimension(49, 25));
        btnSuma.setMinimumSize(new java.awt.Dimension(49, 25));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(102, 102, 102));
        btnTres.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnTres.setForeground(new java.awt.Color(51, 51, 51));
        btnTres.setText("3");
        btnTres.setMaximumSize(new java.awt.Dimension(49, 25));
        btnTres.setMinimumSize(new java.awt.Dimension(49, 25));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnDos.setBackground(new java.awt.Color(102, 102, 102));
        btnDos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDos.setForeground(new java.awt.Color(51, 51, 51));
        btnDos.setText("2");
        btnDos.setMaximumSize(new java.awt.Dimension(49, 25));
        btnDos.setMinimumSize(new java.awt.Dimension(49, 25));
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnUno.setBackground(new java.awt.Color(102, 102, 102));
        btnUno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUno.setForeground(new java.awt.Color(51, 51, 51));
        btnUno.setText("1");
        btnUno.setMaximumSize(new java.awt.Dimension(49, 25));
        btnUno.setMinimumSize(new java.awt.Dimension(49, 25));
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 255, 255));
        btnIgual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(0, 0, 0));
        btnIgual.setText("=");
        btnIgual.setMaximumSize(new java.awt.Dimension(49, 25));
        btnIgual.setMinimumSize(new java.awt.Dimension(49, 25));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(102, 102, 102));
        btnPunto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(51, 51, 51));
        btnPunto.setText(".");
        btnPunto.setMaximumSize(new java.awt.Dimension(49, 25));
        btnPunto.setMinimumSize(new java.awt.Dimension(49, 25));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnCero.setBackground(new java.awt.Color(102, 102, 102));
        btnCero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCero.setForeground(new java.awt.Color(51, 51, 51));
        btnCero.setText("0");
        btnCero.setMaximumSize(new java.awt.Dimension(49, 25));
        btnCero.setMinimumSize(new java.awt.Dimension(49, 25));
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnCambioSigno.setBackground(new java.awt.Color(102, 102, 102));
        btnCambioSigno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCambioSigno.setForeground(new java.awt.Color(51, 51, 51));
        btnCambioSigno.setText("+/-");
        btnCambioSigno.setMaximumSize(new java.awt.Dimension(49, 25));
        btnCambioSigno.setMinimumSize(new java.awt.Dimension(49, 25));

        btnNueve.setBackground(new java.awt.Color(102, 102, 102));
        btnNueve.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNueve.setForeground(new java.awt.Color(51, 51, 51));
        btnNueve.setText("9");
        btnNueve.setMaximumSize(new java.awt.Dimension(49, 25));
        btnNueve.setMinimumSize(new java.awt.Dimension(49, 25));
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        numPantalla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        numPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPantalla.setText("0");
        numPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPantallaActionPerformed(evt);
            }
        });

        lblPantalla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPantalla.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambioSigno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPorciento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOcho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCinco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarMemoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBorrar, btnCambioSigno, btnCero, btnCinco, btnCuatro, btnDivision, btnDos, btnIgual, btnLimpiarMemoria, btnMultiplicacion, btnNueve, btnOcho, btnPorciento, btnPunto, btnResta, btnSeis, btnSiete, btnSuma, btnTres, btnUno});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLimpiarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambioSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBorrar, btnCambioSigno, btnCero, btnCinco, btnCuatro, btnDivision, btnDos, btnIgual, btnLimpiarMemoria, btnMultiplicacion, btnNueve, btnOcho, btnPorciento, btnPunto, btnResta, btnSeis, btnSiete, btnSuma, btnTres, btnUno});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean hayOperador(String texto) {

        for (String operador : operadores) {
            if (texto.endsWith(operador)) {
                return true;
            }
        }
        return false;
    }

    private void operacion(double n1, double n2, String o) {
        if (o == "+") {
            resultado = n1 + n2;
        }
        if (o == "-") {
            resultado = n1 - n2;
        }
        if (o == "*") {
            resultado = n1 * n2;
        }
        if (o == "/") {
            if (n2 == 0) {
                resultado = 0;
            } else {
                resultado = n1 / n2;
            }

        }

    }

    private boolean signo(char letra) {
        for (String operador : operadores) {
            if (letra == operador.charAt(0)) {
                return true;
            }
        }
        return false;
    }

    private void recorrernumtext() {

        if (hayOperador(NumText)) {
            return;
        }
        double n1 = 0;

    }

    private void evaluar() {
        String texto = lblPantalla.getText();
        if (hayOperador(texto)) {
            operacionActual = "";
            return;
        }

    }

    private void btnPorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcientoActionPerformed
        // TODO add your handling code here:
        if (introduciendoNumero) {
            operacionActual = "%";
            introduciendoNumero = false;
            num = Double.parseDouble(numPantalla.getText());
            resultado = num / 100;
            NumText = String.valueOf(resultado);
            lblPantalla.setText(NumText);
            operacionFinalizada = true;
        }


    }//GEN-LAST:event_btnPorcientoActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        if (hayOperador(NumText)) {
            return;
        }

        operacionActual = "+";
        if (operacionFinalizada) {
            num = resultado;
            num = Double.valueOf(lblPantalla.getText());
            System.out.println(num);
            evaluar();
            NumText = operacionActual;
        }

        lblPantalla.setText(NumText);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:

        operacionActual = "-";
        num = Double.valueOf(numPantalla.getText());
        evaluar();

        NumText += operacionActual;
        lblPantalla.setText(NumText);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
        operacionActual = "*";
        num = Double.valueOf(lblPantalla.getText());
        evaluar();
        NumText += operacionActual;
        lblPantalla.setText(NumText);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        operacionActual = "/";
        num = Double.valueOf(lblPantalla.getText());
        evaluar();
        NumText += operacionActual;

        lblPantalla.setText(NumText);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void op(String n) {
        introduciendoNumero = true;
        if (operacionFinalizada) {
            NumText = n;

            operacionFinalizada = false;
        } else {
            NumText += n;
        }
    }

    private void ObteniendoNumero(double n) {

    }
    
    private void intNumero(String numero) {

        System.out.println(numero);
        op(numero);

        lblPantalla.setText(NumText);
        if (introduciendoNumero) {
            String te = numPantalla.getText();
            te += numero;
            if (te == "0") {
                te = numero;
            }

            numPantalla.setText(te);
        }
    }
    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        intNumero("1");

    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        intNumero("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
        intNumero("2");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        // TODO add your handling code here:
        intNumero("3");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
        intNumero("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
        intNumero("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        intNumero("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        // TODO add your handling code here:
        intNumero("8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        // TODO add your handling code here:
        intNumero("9");

    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        NumText += "0";
        lblPantalla.setText(NumText);
        numPantalla.setText(String.valueOf(0));
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        if (operacionFinalizada) {
            NumText = "0.";
            operacionFinalizada = false;
        } else {
            NumText += ".";
        }
        lblPantalla.setText(NumText);
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        if (operacionActual == "") {
            return;
        }
        recorrernumtext();

        double n = Double.valueOf(NumText);
        lblPantalla.setText(String.valueOf(n));

        evaluar();
    }//GEN-LAST:event_btnIgualActionPerformed

    private void numPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCambioSigno;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiarMemoria;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPorciento;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JTextField numPantalla;
    // End of variables declaration//GEN-END:variables
}
